---
- hosts: hostlocal
  connection: local

  tasks:
  - assert:
      that:
          - ansible_memtotal_mb >= 128


  - name: OS and Kernel info
      vars:
        msg: |
        Distribution: {{ ansible_distribution }}
        Kernel: {{ ansible_kernel }}
        Architecture: {{ ansible_architecture }}
        RAM: {{ ansible_memtotal_mb }}
        Host: {{ansible_hostname }}
        MemFree: {{ ansible_memfree_mb }}
        ProcessorType: {{ ansible_processor }}
      debug:
        msg: "{{ msg.split('\n') }}"
